# Generated by Django 3.2.5 on 2025-01-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_dashboard_excelfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inflation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('bpmos_medical_inflation', models.DecimalField(decimal_places=2, help_text='Enter BPMOS Medical Inflation (%)', max_digits=5)),
                ('general_inflation', models.DecimalField(decimal_places=2, help_text='Enter General Inflation (%)', max_digits=5)),
            ],
        ),
    ]
